name: Java CI

on: 
  push:
    branches: 
      - develop
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn install -B package --file pom.xml
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/runner/work/TUMineCity/TUMineCity/target/*.jar"
<<<<<<< HEAD:.github/workflows/maven_install_master.yml
        target: "/home/generalmine/server/minecraft/TUMine/plugins"
=======
        target: "/home/generalmine/server/minecraft/testServer/plugins"
>>>>>>> 711735445213f12fba1e542057e321329e160599:.github/workflows/maven_install_develop.yml
        strip_components: 3
